// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxJEqxEhVVELBvNzzdG-6plRpqLmzS1rg',
    appId: '1:193827802677:web:7ff648c03004f41a75eb7c',
    messagingSenderId: '193827802677',
    projectId: 'smarthome-802c9',
    authDomain: 'smarthome-802c9.firebaseapp.com',
    databaseURL: 'https://smarthome-802c9-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-802c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMS-V6x0mBrOPZu2kQq1pjNAnbkg8I6c4',
    appId: '1:193827802677:android:369ec6a89a8e852a75eb7c',
    messagingSenderId: '193827802677',
    projectId: 'smarthome-802c9',
    databaseURL: 'https://smarthome-802c9-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-802c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1DfRq_uNzeMScY54Om_xdZBp8wsPt5Q',
    appId: '1:193827802677:ios:b18e617527e474d575eb7c',
    messagingSenderId: '193827802677',
    projectId: 'smarthome-802c9',
    databaseURL: 'https://smarthome-802c9-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-802c9.firebasestorage.app',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1DfRq_uNzeMScY54Om_xdZBp8wsPt5Q',
    appId: '1:193827802677:ios:b18e617527e474d575eb7c',
    messagingSenderId: '193827802677',
    projectId: 'smarthome-802c9',
    databaseURL: 'https://smarthome-802c9-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-802c9.firebasestorage.app',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxJEqxEhVVELBvNzzdG-6plRpqLmzS1rg',
    appId: '1:193827802677:web:2fc707673b28f58175eb7c',
    messagingSenderId: '193827802677',
    projectId: 'smarthome-802c9',
    authDomain: 'smarthome-802c9.firebaseapp.com',
    databaseURL: 'https://smarthome-802c9-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-802c9.firebasestorage.app',
  );
}
